### ISSUE TITLE
Create issue example.

### ISSUE THREAD

**Issue by casperOne** [dapplo/Dapplo.Jira#11]
I'm following the code to create an issue in JIRA.  

I'm able to query, search, etc. issues, issue types, projects, etc.

However, when I try and call `CreateSync`, I keep getting an exception, the status code being 400 and then message being `Bad Request`.

I'm using the code from `IssueTests`:

https://github.com/dapplo/Dapplo.Jira/blob/master/Dapplo.Jira.Tests/IssueTests.cs#L50

Is there any way I can see the JSON that is being serialized on the wire, or how I can gain more insight into what's happening here?

**Comment by Lakritzator** [comment]
Did you update to the latest release, this was added **very recently** and had a small bug as it serialized a null value (which doesn't make sense) in the project information causing a 400.
Still this might not solve it as Jira is actually quite "restrictive",and I probably still need to add something to get the error up to the caller.


Yes, you can see what is happening, for instance to follow this when running as Debug in VS and you want to see it in the console do the following:
Add nuget package "Dapplo.Log.Loggers", if it isn't already and add the following before doing anything:
```
// Make all Dapplo code use a DebugLogger with level Verbose
LogSettings.RegisterDefaultLogger<DebugLogger>(LogLevels.Verbose);
// Make sure the complete Json response is logged, by removing the log threshold
DefaultJsonHttpContentConverter.Instance.Value.LogThreshold = 0;
```
With this, the underlying HttpClient framework (Dapplo.HttpExtensions) and also small parts of Dapplo.Jira will log to the Debug output.

P.S.
Another way is to install Fiddler, as the communication is HTTP this works very good.

**Comment by Lakritzator** [comment]
Just make sure you use 0.5.20 or higher, as the library is just now starting to get usable I didn't write many release notes yet...

**Comment by casperOne** [comment]
@Lakritzator I was on 0.5.19.  I've updated to 0.5.21.

Unfortunately, I'm still getting a bug.

I've found the issue though.  You're not serializing custom fields on the wire when creating the issue.

Here's a screenshot of me stepping through my code setting the appropriate custom field on the `Issue` object:

![image](https://cloud.githubusercontent.com/assets/561862/22622155/28f88778-eb01-11e6-961f-653c8c5b2944.png)

However, logging the request shows that custom fields aren't serialized and sent to the server (and the [current test](https://github.com/dapplo/Dapplo.Jira/blob/18ca0114aabb74f70b18edd825c2c95f91fa5aaf/Dapplo.Jira.Tests/IssueTests.cs#L63) doesn't have a test for custom fields.

Here's the JSON that's sent over:

```
{
  "fields": {
    "issuetype": {
      "description": "A big user story that needs to be broken down. Created by JIRA Software - do not edit or delete.",
      "iconUrl": "https://<my server>.atlassian.net/images/icons/issuetypes/epic.svg",
      "name": "Epic"
    },
    "project": {
      "key": "<my project key>"
    },
    "summary": "Test"
  }
}
```

My JIRA instance requires the custom field on the `Issue` that I'm trying to create, therefore the return response is:

```
{
    "errorMessages":[],
    "errors":{
        "customfield_10017":"Epic Name is required."
    }
}
```

So the underlying issue is: how can we get the custom fields serialized over in the call to create an `Issue`?

**Comment by Lakritzator** [comment]
That is good information, thanks a lot.

There are a couple of things which need improvement:

1. I will add a better error handling to Dapplo.Jira
2. I have to add serializing of the "ExtensionData"
3. I still have to add Epics to the Agile domain, and you might also need to go via Agile to create "agile" issues in the future.

Anyway, will check this.

**Comment by casperOne** [comment]
@Lakritzator Any way we can get a quick build that handles serializing the `CustomFields` correctly?  That's the only thing that's stopping me at this point from creating issues.

Currently, the library works with Epic types, in that if you look for the `IssueType` and then attach it to the `Issue` it serializes correctly across the wire.

**Comment by Lakritzator** [comment]
Update: I think I got the serializer in the underlying framework, my Dapplo.HttpExtensions, to work in such a way that it will work... now I want to fix the error handling and add my changes (had to change some classes) to Dapplo.Jira.

**Comment by Lakritzator** [comment]
I worked hard to make a fix, unfortunately due to a time problem I have only been able to fix this according to some test cases. (So in theory it's fixed) But I haven tested any call with a custom field yet...

But I also do have a personal life 😄 

I hope this works for you... please let me know.

**Comment by casperOne** [comment]
@Lakritzator Is there a new NuGet package for this build?

**Comment by Lakritzator** [comment]
It should be around the corner, with the commit a build on my CI-system was triggered.
A yes, it failed as my jira sometimes gives me an empty response where it shouldn't, I restarted and 0.5.23 was just pushed!

The error with the empty response which fails my integration tests COULD be in Dapplo.Jira too, as I have a lot of test cases running parallel... **maybe** a concurrency issue, which would be weird but I will find it.

**Comment by Lakritzator** [comment]
found it?

**Comment by casperOne** [comment]
Yes, will test in a little bit.  Will report back ASAP.

**Comment by Lakritzator** [comment]
i go to sleep now

**Comment by casperOne** [comment]
The custom fields are being serialized when issues are created, so this is addressed for now, thanks!

**Comment by Lakritzator** [comment]
Thanks for the update!
I will still need to check if everything is serialized okay when custom fields have complex content.
