### ISSUE TITLE
Edit Issues

### ISSUE THREAD

**Issue by casperOne** [dapplo/Dapplo.Jira#12]
I notice there are no methods on `IIssueDomain` to edit an issue.

How can I edit an issue?

**Comment by Lakritzator** [comment]
Will add this, as UpdateAsync, maybe today or tomorrow.
It might not be so easy, as during the update only certain fields are allowed to be written.... so I will need to mark all other values in the Issue with a ReadOnly attribute.

**Comment by Lakritzator** [comment]
Just had a look, it actually doesn't work like I expected. (like "update")
I need to see how this can be implemented.

No worries, I will find a solution 😄

**Comment by Lakritzator** [comment]
I actually did get it working as I though, at least it looks like that..
Not 100% happy with the result though, you will need to do it like this:
https://github.com/dapplo/Dapplo.Jira/blob/master/Dapplo.Jira.Tests/IssueTests.cs#L50

**Comment by casperOne** [comment]
This seems to work in 0.5.23.  I was able to update.

Round tripping (searching for an object and then adding it) may have some issues related to fields visibility on screen.

That said, copying the values to a new `Issue` object works.

This is closed, as there is edit functionality.  I'll add new tickets for some other little items related to it, as they are really extensions of the edit functionality.
