### ISSUE TITLE
Support notify users, override screen security and override editable flag when calling UpdateAsync for Issues.

### ISSUE THREAD

**Issue by casperOne** [dapplo/Dapplo.Jira#15]
It would be great if we could pass the `notifyUsers`, `overrideScreenSecurity` and `overrideEditableFlag` flags as per the [documentation for edit issue](https://docs.atlassian.com/jira/REST/cloud/#api/2/issue-editIssue).

**Comment by Lakritzator** [comment]
Yes, I'll gladly add that as it's an easy change.

**Comment by Lakritzator** [comment]
Dapplo.Jira 0.5.25 was build & published for this

Currently I do not have a test case for this, as creating the prerequisites is currently not so easy as just adding the fields to the request URI.

But in this case I think you have a use-case for it, and can already use it without waiting for me to set this up...

**Comment by Lakritzator** [comment]
Hi @casperOne, did you manage to have a look at this?

**Comment by casperOne** [comment]
I'm hoping to test it tonight or tomorrow night.

**Comment by casperOne** [comment]
Closing the issue, these flags work as expected.  I tried them and was given an expected error that I didn't have permissions to use the override flags.

Thanks!
