### ISSUE TITLE
Extension "TimeSpanExtensions.ToWorkingTime(TimeSpan,TimeTrackingConfiguration )" is  worked wrong

### ISSUE THREAD

**Issue by vik-borisov** [dapplo/Dapplo.Jira#19]
For example, i have a TimeSpan with 1 hour.
Result of work extension is: "0,125d 1h"

`var workingDays = hours / timeTrackingConfiguration.WorkingHoursPerDay;` 
**hours** is _int_ and **WorkingHoursPerDay** is _float_. Result is _float_.

```
if (workingDays > 0)
{
   jiraTimeRange.AppendFormat("{0}d ", workingDays);
}
```
Condition is wrong

**Comment by Lakritzator** [comment]
Thanks, I will check this tomorrow. This bug was introduced due to a needed change in the working days type (as non integer values are possible.)
