### ISSUE TITLE
Cannot find xunit tests in test explorer

### ISSUE THREAD

**Issue by alfadormx** [dapplo/Dapplo.Jira#21]
Hi,

Could you please help me out? I have VS Studio 2015 Update 3 Professional with the .NET Core Tools for VS20015. I cannot see the Xunit tests in the Test Runner window. I would like to add some endpoints and the associated tests for them. The problem is I don't see the tests so I cannot execute them. What is your PC configuration?

Thanks
HH

**Comment by Lakritzator** [comment]
thanks for asking, I really appreciate some help 😊
There was an issue with the recent xunit update, so I just downgraded this.

Try again, please.

Btw. You will need to supply your own server & credentials for the tests, checkout the TestBase.cs

Best wishes,
Robin

**Comment by alfadormx** [comment]
Thanks for your help. I have updated the code and I can see the tests.
