### ISSUE TITLE
Issue fetching additional issues from JIRA

### ISSUE THREAD

**Issue by PauluVZ** [dapplo/Dapplo.Jira#24]
HI, I have the following issue.

Let's say I want to retrieve a list of all JIRA issues, (currently around 16000 issues). I do know that for my current JIRA implementation, I am limited to retrieving maximum 1000 issues at a time.

However, I cannot figure out a way to retrieve the first 1000, then the second 1000, etc until I have retrieved all 16000.
My current c# code (still in progress) is as follows, where I thought to retrieve the first 1000, then set the start value to the next 1000, but it keeps on returning the first 1000 issues only. How do I go about to do this?

```
var jiraIssue = jiraClient.Issue;
var searchResult = await jiraIssue.SearchAsync("project in (XXXX) AND (summary ~ Report OR assignee = \"myusername\") AND Status != Closed ORDER BY key ASC", 1000);
do
{
              
                string str = "StartAt: " + searchResult.StartAt.ToString() +
                             "\nMaxResults: " + searchResult.MaxResults.ToString() +
                             "\nTotal: " + searchResult.Total.ToString();
                if (searchResult.IsLast)
                    str = str + "\nIsLast: true";
                else
                    str = str + "\nIsLast: false";
                //MessageBox.Show(str, "Ticket Metrics", MessageBoxButtons.OK, MessageBoxIcon.Information);

                foreach (var issue in searchResult.Issues)
                {
                    listView1.Items.Add(issue.Key);
                }
                searchResult.StartAt += searchResult.MaxResults;
                searchResult = await jiraIssue.SearchAsync("project in (XXXX) AND (summary ~ Report OR assignee = \"myusername\") AND Status != Closed ORDER BY key ASC", 1000);
} while (!searchResult.IsLast);
```

**Comment by Lakritzator** [comment]
The startAt argument is missing in the method, I will add this.

**Comment by Lakritzator** [comment]
This is my suggested solution, the changes which make this possible are not yet available.

```
	        // var query = "project in (XXXX)AND(summary ~Report OR assignee = \"myusername\") AND Status != Closed ORDER BY key ASC"
	        var query = Where.And(Where.Project.In("XXXX"), Where.Or(Where.Summary.Contains("Report"), Where.Assignee.Is("myusername")), Where.Status.Is("Closed")).OrderByAscending(Fields.IssueKey);
	        var searchResult = await Client.Issue.SearchAsync(query);

	        // Loop over all results
	        do
	        {
	            Assert.NotNull(searchResult);
	            Assert.NotNull(searchResult.Issues.Count > 0);
	            Log.Info().WriteLine("Got {0} results, starting at index {1}, isLast: {2}", searchResult.Total, searchResult.StartAt, searchResult.IsLastPage);
	            if (searchResult.IsLastPage)
	            {
	                break;
	            }
	            searchResult = await Client.Issue.NextPageSearchAsync(searchResult);
	        } while (true);
```

**Comment by PauluVZ** [comment]
Dear Lakritzator, thank you this is indeed awesome news, I was just wondering if you have any idea yet when these changes might become available?

**Comment by Lakritzator** [comment]
As soon as I can explain my build script to run on the build server with dotnet core... hopefully in the next ~30 minutes.

**Comment by Lakritzator** [comment]
0.7.3 is made available on nuget.org, please have a try and let me know if this works for you so I can close this ticket.

**Comment by PauluVZ** [comment]
Dear Lakritzator

I have updated my code accordingly with the new package. This is working perfectly, thank you so much.

**Comment by Lakritzator** [comment]
Thanks for the feedback.

I will need to update my documentation (and my site) anyway... 
The 0.6.x is still hosted here: http://www.dapplo.net/documentation/Dapplo.Jira/

Will update and add an article on the subject of paging, you are ofcource more than welcome to add documentation yourself :)
