### ISSUE TITLE
How to construct a where clause?

### ISSUE THREAD

**Issue by asdf23** [dapplo/Dapplo.Jira#25]
I'm trying to implement a complex where clause, well not too complex. Where the issue is assigned to any of a username and the status != closed.

```
string [] usersToWatch = ...
SearchAsync(Where.Assignee.In(usersToWatch)
```

I also see `Where.Status.Not` but I do not see a way to combine these into a single statement

**Comment by Lakritzator** [comment]
Hi,

you can use the Where.And and Where.Or to combine queries.
Where.And(Where.Assignee.In(usersToWatch), Where.Status.Not.., Where....)

Let me know if this works for you!

Best wishes,
Robin

**Comment by asdf23** [comment]
I see thank you, (this is what I was trying to in the example)
```
JiraClient.Issue.SearchAsync(
    Where.And(
        Where.Assignee.In(usersToWatch)
        ,Where.Status.Not.Is("Closed")
    )
);
```
