### ISSUE TITLE
How can I implement ContinueWith?

### ISSUE THREAD

**Issue by asdf23** [dapplo/Dapplo.Jira#26]
I'd like to pass a delegate to the search method so that the data is processed when it arrives, avoiding the use of `await`. Completely running in the background. I'm having trouble implementing it. Here is what I have so far...

```
    public class Program
    {
        .....
        public void SomeEventFiredOff(object sender, ...)
        {
            SomeStaticClass.PullIssuesByAssignee(UpdateItems); //Call to Dapplo.Jira
        }
        
        //Process results from Dapplo.Jira
        public int UpdateItems(SearchIssuesResult<Issue, JqlIssueSearch> issues)
        {
               foreach (Dapplo.Jira.Entities.Issue issue in issues)
               { 
                  ...
               }
        }
     }
```

```
     public static class SomeStaticClass
     {
         //Working
         public void PullIssuesByAssignee(Func<SearchIssuesResult<Issue, JqlIssueSearch>,int> OnComplete)
         {
               ....
               Task<SearchIssuesResult<Issue, JqlIssueSearch>> myAssignedIssues = JiraConnection.Issue.SearchAsync(Where.Assignee.In(usersToWatch));
               myAssignedIssues.Wait(); // <--- how can I not Wait?
               OnComplete(myAssignedIssues.Result);
         }
         //Instead I want to write this code:
         public void PullIssuesByAssignee(Func<SearchIssuesResult<Issue, JqlIssueSearch>,int> OnComplete)
         {
               ....
               Task<SearchIssuesResult<Issue, JqlIssueSearch>> myAssignedIssues = JiraConnection.Issue.SearchAsync(Where.Assignee.In(usersToWatch));
               myAssignedIssues.ContinueWith(  OnComplete(  myAssignedIssues  ) ) // <-- Invalid line
         }
     }
```

How can I implement ContinueWith, passing it a method such as UpdateItems?

**Comment by Lakritzator** [comment]
This is a more generic C# question, doesn't directly have to do with my library.
I advice you to readup a bit on the async functionality of C#, it might take a bit of time to get used to, but this opens up some very very very cool possibilities!!

The "problem" with async code, is that you should not try to use it synchronously, this can give you very bad side effects... If you can, use async methods and await to wait for the result.
.Result and .Wait() can make your application hang in a deadlock!
Really really try that, you will get into so much problems without using async & await!

If you don't want to have an await in your DIRECT code, use it indirectly!

Here is an example, this will create a task, running in the background and search Jira, wait for the result and than pass it to the other method.

Task.Run(async () => {
var myAssignedIssues  = await JiraConnection.Issue.SearchAsync(Where.Assignee.In(usersToWatch));
OnComplete(  myAssignedIssues  );
});

Do note, the task is running in the background, you cannot simply change the UI.
And you don't really know if the task is finished with this solution, you might create them quicker as they are processed.. also you might cause threading issues with mutiple OnComplete calls parallel.

As I don't know what you want to achive, you might add some more information for a better example.

In general, if you have a UI with for example a button, you implement the on click like this: (async void is not adviced, but for events this is accepted)
```
private async void OnButtonClick(object sender, eventargs...) {
 button.IsEnabled = false;
 var myAssignedIssues  = await JiraConnection.Issue.SearchAsync(Where.Assignee.In(usersToWatch));
UpdateItems(myAssignedIssues);
 button.IsEnabled = true;
}
```

Hope this helps, but to repeat myself, the best thing to do is learn to use async await... it REALLY pays off!

**Comment by asdf23** [comment]
Hello thanks for the comment, I will try it. I'm writing a logger like tool (think tail --follow) So I'm not locking  up a UI and I do want a true asynchronous result.
