### ISSUE TITLE
Retrieve changelogs for an issue

### ISSUE THREAD

**Issue by jgrossrieder** [dapplo/Dapplo.Jira#27]
Hi,

I didn't found how to retrieve the changelogs for a given issue in JIRA, is this possible? Or it has not been implemented?

For a JIRA API point of view, I think it has to do with expand=changelog?

Thanks

**Comment by jgrossrieder** [comment]
@Lakritzator Will you integrate this soon? If yes, I will probably add some other things.

**Comment by Lakritzator** [comment]
Yes, more than happy to do so.

Off topic:
For the next big step, I was thinking of moving to Flurl. Anything against that?
When I started this, it was not usable so I wrote my own HttpClient stuff...
They got more popular 😄

**Comment by jgrossrieder** [comment]
@Lakritzator I'm not familiar with it, but I'm a quick learner ;)

**Comment by Lakritzator** [comment]
You don't need to learn much, the basics are the same.
It's just that Dapplo.HttpExtensions is nice, but Flurl is better supported.
And I knew when I wrote it, that I might need to replace it some day.

**Comment by Lakritzator** [comment]
With the merge of the PR #28, and build of Dapplo.Jira 0.7.15, this can be closed.

Thanks a lot Julien
