### ISSUE TITLE
Jira User API changing due to GDPR, action needed

### ISSUE THREAD

**Issue by LUS1N** [dapplo/Dapplo.Jira#39]
From 2019-03-29 user will no longer will be fetchable by username and will need to be fetched by accountId.

This SDK should use accountId query param to get the user as well.

https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-api-3-user-get

https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/

**Comment by LUS1N** [comment]
@Lakritzator @jlopresti  @alfadormx @rualert 

will any of you merge this if i submit a pull request or is this project dead?

**Comment by Lakritzator** [comment]
Sorry, no it's not dead, I just somehow didn't get any emails on this... weird.
I need to look at it.

**Comment by Lakritzator** [comment]
Back than I didn't notice any issues in general, but now I finally saw what you meant.

Your URL was somehow off, it should have been this:
https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-rest-api-3-user-get

Using a accountId doesn't make things easier... I wonder why this is now so complicated, it feels a bit like a hack to improve performance.

So I will need to test & modify everything in the UserExtensions.cs
Any tipps?

**Comment by Lakritzator** [comment]
P.S.
I've changed the License to MIT, which is more popular than LGPL-3.0 and should make things a bit easier. I hope that is okay with you? https://www.nuget.org/packages/Dapplo.Jira/0.9.8

**Comment by LUS1N** [comment]
@Lakritzator this is not because of performance, but because of GDPR. I guess the user name is now sensitive information that they would rather not use.

Sorry no tips on the codebase, I'm not overly familiar with it.

**Comment by Lakritzator** [comment]
I've implemented changes for this, and these are available in the latest version.

The changes are only for the Cloud version of JIRA, there are no changes if you use JIRA Server.
You can no longer retrieve a user by username on cloud.
