### ISSUE TITLE
Custom fields cannot be retrieved

### ISSUE THREAD

**Issue by salviri** [dapplo/Dapplo.Jira#40]
When using below code:
var searchResult = jiraClient.Issue.SearchAsync(Where.Project.In(args[3])).Result;

The custom fields are not populated in the dataset.

**Comment by Lakritzator** [comment]
By default result of a search is limited to the bare minimum, this is called a digest, needed to work with the issue. On the other hand, if you do a `var issue = await Client.Issue.GetAsync(issueKey);` the custom fields are there.

It's possible to customise the search in such a way that this information is returned, although this puts a higher load on the server. Still if you are going to retrieve the custom fields for every found issue anyway, you are probably better off getting the information in the search itself.

In the search you can specify what fields to use, this would for instance work:
`var searchResult = await Client.Issue.SearchAsync(Where.Project.In(args[3]), fields: new[]{"*all"});`
The default when you don't specify the fields yourself, is specified in https://github.com/dapplo/Dapplo.Jira/blob/master/src/Dapplo.Jira/JiraConfig.cs#L75

You could set your own specific (custom) fields for every search, do this **once**:
`JiraConfig.SearchFields = JiraConfig.SearchFields.Concat(new [] {"customfield_10370", "customfield_10371" }).ToArray();`

After this, every search will include the specified (custom) fields, **if they exist**. Be aware: the names of the custom fields must NOT be the same over multiple JIRA installations!

A bit more information about the fields: https://community.atlassian.com/t5/Answers-Developer-Questions/API-JQL-search-results-provide-way-too-much-information/qaq-p/486398

Let me know if this helps!

btw... **if** possible do not use the API in a non async way.
