### ISSUE TITLE
GetSprintsAsync returns IsLastPage as true always

### ISSUE THREAD

**Issue by mrdixit** [dapplo/Dapplo.Jira#45]
When using GetSprintsAsync, the result set is for MaxItems 50 and IsLastPage is true even though there are more than 100 sprints in board.
When using '/rest/agile/1.0/board/{id}/sprint' directly on browser, I can see isLast is false for initial request.
I am unable to use paging for this request to get all the sprints.

Is there any other way to achieve this?

**Comment by Lakritzator** [comment]
Hello!

Sounds like a bug, let me check.
Are you using cloud or server, if server what version?

Best wishes 
Robin

**Comment by mrdixit** [comment]
Hi @Lakritzator,

Thanks for quick response.
Its server with version 8.5.3

**Comment by Lakritzator** [comment]
Thanks, I'm not sure when have time as I have done other stuff on my open source list. But I hope to at least have a quick look tonight (kid and all...)

It's sometimes hard to support this, as I don't always have access to a jira server and even using the cloud version with certain combinations is a challenge. So depending on the bug, it might be something small or an deviation between cloud and server which is harder to test. Last week I had such an issue with confluence, but it seems that was fixed.

I was going to run a jira for development on a container on my laptop but its memory is not enough to have visual studio and docker running without having a huge performance impact 😢 and the SSD seems faulty as it's slow. It's a Surface Pro from 2017, 8GB/256GB and it got problems right after the warranty ended.... It still has to keep running until start of next year, hope it doesn't get worse...

I'll try to fire up an old PC and see if docker works there... It's the same thing with my confluence project, so I'll need  a solution to support those without being dependent on the jira from work.

Btw Your company is more than welcome to sponsor my work 😉

Anyway if I did something I'll let you know.

**Comment by mrdixit** [comment]
Thanks a lot @Lakritzator for the effort you are putting in.
I am just trying out some API's to do a learning on JIRA.

Again, appreciate your work a lot. :)

**Comment by Lakritzator** [comment]
I had a quick look yesterday. The IsLastPage property is calculated and not matching the value from the jason, I need to setup a test instance to be able to track this. I don't like the pageing support like it's right now. The agile part was merged into jira by Atlassian  later and somehow doesn't fit 100% the rest of the API. And I probably assumed it was the same...

I will solve this ... Can't estimate yet when.

**Comment by Lakritzator** [comment]
Okay I have made some changes, can you try it now with the latest version.

**Comment by Lakritzator** [comment]
Btw, Atlassian provides a docker image which can be installed with a demo project and issues.
I was able to get docker running on an older PC, so I didn't have pay the penalty of not having enough memory on the system where I develop with Visual Studio. It's not very fast, but it somehow does work.

**Comment by Lakritzator** [comment]
FYI, the version where this should be solved is (Dapplo.Jira 0.9.26)[https://www.nuget.org/packages/Dapplo.Jira/0.9.26]

**Comment by mrdixit** [comment]
Hi @Lakritzator , 

I pulled the latest last night and the paging seems to be working.
Thanks a lot for fixing this.

**Comment by Lakritzator** [comment]
I hope that with "pulled" you mean the nuget package, and are not using the sources directly...

Thanks for the feedback, and closing this.

**Comment by mrdixit** [comment]
yes, it was update via nuget. :)
