### ISSUE TITLE
Reference SVG in Dapplo.Jira

### ISSUE THREAD

**Issue by toertchn** [dapplo/Dapplo.Jira#54]
The referencing package "SVG" can apparently be removed from Dapplo.Jira.
It's only used in "Dapplo.Jira.SvgWinForms"?

**Comment by Lakritzator** [comment]
Good catch, I moved the code to a separate package to make the library better usable from linux and somehow I forgot this.
Consider it removed with the next version.

**Comment by Lakritzator** [comment]
Removed Svg from Dapplo.Jira with 1.1.27
