### ISSUE TITLE
Is there a way to get the parent key for an issue

### ISSUE THREAD

**Issue by richardwarriner** [dapplo/Dapplo.Jira#72]
Hi

I am migrating away from https://bitbucket.org/farmas/atlassian.net-sdk/src/master/ now it has been abandoned and have come up with a problem. 

Part of my application groups issues by their parent and when querying issues using Dapplo the parent issue id doesn't seem to be available? Am I missing something or is it not there? 

If it's not would it be possible to add support for it? Its quite essential for what I am trying to do

Many thanks

**Comment by Lakritzator** [comment]
Hi,

yeah that is certainly possible, so far this wasn't needed.

I run this repository not with the focus on being complete, I do not have the resources (time) for that, but with the focus on what is needed.

I've added the Parent information, to Dapplo.Jira version 1.1.44 which should be available in a few minutes (unless Nuget is slow), for example see [here](https://github.com/dapplo/Dapplo.Jira/blob/master/src/Dapplo.Jira.Tests/IssueTests.cs#L244)

Let me know if this helps, so I can close this issue.

Best wishes
Robin

**Comment by Lakritzator** [comment]
Btw. if you are going via search (JQL), I'm not sure if the parent information is extended, if not please make sure you specify the fields you want to have (in that case "parent").

e.g. https://github.com/dapplo/Dapplo.Jira/blob/master/src/Dapplo.Jira.Tests/IssueTests.cs#L318

**Comment by richardwarriner** [comment]
That seems to be coming through ok. I appreciate you finding the time to add it and understand your comments regarding the focus of this project. For me personally, I think it now gives me everything I need. The only other fields I use are all custom so I can get those easily enough.
I sent you PayPal tip :)

**Comment by Lakritzator** [comment]
Thanks for the feedback, and the tip.

Let me know if you find anything else, I'm usually very busy with Greenshot (for which this was initially written) and some of my other work, but generally find time to look at things. And this is not the best documented project, so don't hesitate to ask, after looking at the test cases first 😉 

Closing this.
