### ISSUE TITLE
User impersonation

### ISSUE THREAD

**Issue by KerosenoDev** [dapplo/Dapplo.Jira#73]
Hi. Is it possible to authenticate using user impersonation?

[https://developer.atlassian.com/cloud/jira/platform/user-impersonation-for-connect-apps/](https://developer.atlassian.com/cloud/jira/platform/user-impersonation-for-connect-apps/)

**Comment by Lakritzator** [comment]
I don't know, need to look at it.

But can you explain the use-case for this? What do you hope to achieve with it?

**Comment by KerosenoDev** [comment]
In my case, a supplier requires to authenticate without user and password/token (basic auth), and I don't know how.

**Comment by Lakritzator** [comment]
I'm still not sure how Dapplo.Jira comes into that? So do you need to write an application, or already have one, where you want to offer a supplied to authenticate?

**Comment by KerosenoDev** [comment]
Discarded. Thank you anyway.
